### ISSUE TITLE
New IR Code for faber

### ISSUE THREAD

**Issue by Bobsilvio** [Tomasinjo/hob2hood-faber#1]
Hi, thanks to your tool and the IR codes I managed to configure a working ESP. However, in my case the IR code of a DROP is missing..
not having the remote control how can I recover it?

new IR: https://www.faberspa.com/products/accessorio-telecomando-faber-air-hub-bt-ir

thanks

**Comment by Tomasinjo** [comment]
You can't find the code for DROP without the remote. If you can get one, you can use something like below to read it and add it.
https://github.com/Arduino-IRremote/Arduino-IRremote/blob/master/examples/ReceiveDemo/ReceiveDemo.ino

Another way is to find some other project here on Github from people that managed to get it. If you find it, make sure to create a pull request :)
